config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cinemas
  resources :veeresh_accounts
  resources :movies
  resources :feedbacks
  resources :bookings

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
belongs_to :user
validates_presence_of :seating_comfort,:ac,:movie_video_output,:movie_audio_quality


end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:seating_comfort, :ac, :movie_audio_quality, :movie_video_output, :suggestion, :complaint, :user_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seating_comfort %><br>
    <%= f.text_field :seating_comfort %>
  </div>
  <div class="field">
    <%= f.label :ac %><br>
    <%= f.text_field :ac %>
  </div>
  <div class="field">
    <%= f.label :movie_audio_quality %><br>
    <%= f.text_field :movie_audio_quality %>
  </div>
  <div class="field">
    <%= f.label :movie_video_output %><br>
    <%= f.text_field :movie_video_output %>
  </div>
  <div class="field">
    <%= f.label :suggestion %><br>
    <%= f.text_field :suggestion %>
  </div>
  <div class="field">
    <%= f.label :complaint %><br>
    <%= f.text_field :complaint %>
  </div>


  <%= f.hidden_field :user_id,:value => params[:user_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Seating comfort</th>
      <th>Ac</th>
      <th>Movie audio quality</th>
      <th>Movie video output</th>
      <th>Suggestion</th>
      <th>Complaint</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.seating_comfort %></td>
        <td><%= feedback.ac %></td>
        <td><%= feedback.movie_audio_quality %></td>
        <td><%= feedback.movie_video_output %></td>
        <td><%= feedback.suggestion %></td>
        <td><%= feedback.complaint %></td>
        <td><%= feedback.user_id %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seating comfort:</strong>
  <%= @feedback.seating_comfort %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @feedback.ac %>
</p>

<p>
  <strong>Movie audio quality:</strong>
  <%= @feedback.movie_audio_quality %>
</p>

<p>
  <strong>Movie video output:</strong>
  <%= @feedback.movie_video_output %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @feedback.suggestion %>
</p>

<p>
  <strong>Complaint:</strong>
  <%= @feedback.complaint %>
</p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>