config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cinemas
  resources :veeresh_accounts
  resources :movies
  resources :feedbacks
  resources :bookings

end

app/models/veeresh_account.rb
class VeereshAccount < ActiveRecord::Base
belongs_to :cinema
belongs_to :booking
belongs_to :users
validates_presence_of :no_of_ticket_online,:no_of_ticket_box,:total_amt_per_day

end

app/controllers/veeresh_accounts_controller.rb
class VeereshAccountsController < ApplicationController
  before_action :set_veeresh_account, only: [:show, :edit, :update, :destroy]

  # GET /veeresh_accounts
  # GET /veeresh_accounts.json
  def index
    @veeresh_accounts = VeereshAccount.all
  end

  # GET /veeresh_accounts/1
  # GET /veeresh_accounts/1.json
  def show
  end

  # GET /veeresh_accounts/new
  def new
    @veeresh_account = VeereshAccount.new
  end

  # GET /veeresh_accounts/1/edit
  def edit
  end

  # POST /veeresh_accounts
  # POST /veeresh_accounts.json
  def create
    @veeresh_account = VeereshAccount.new(veeresh_account_params)

    respond_to do |format|
      if @veeresh_account.save
        format.html { redirect_to @veeresh_account, notice: 'Veeresh account was successfully created.' }
        format.json { render :show, status: :created, location: @veeresh_account }
      else
        format.html { render :new }
        format.json { render json: @veeresh_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veeresh_accounts/1
  # PATCH/PUT /veeresh_accounts/1.json
  def update
    respond_to do |format|
      if @veeresh_account.update(veeresh_account_params)
        format.html { redirect_to @veeresh_account, notice: 'Veeresh account was successfully updated.' }
        format.json { render :show, status: :ok, location: @veeresh_account }
      else
        format.html { render :edit }
        format.json { render json: @veeresh_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veeresh_accounts/1
  # DELETE /veeresh_accounts/1.json
  def destroy
    @veeresh_account.destroy
    respond_to do |format|
      format.html { redirect_to veeresh_accounts_url, notice: 'Veeresh account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veeresh_account
      @veeresh_account = VeereshAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veeresh_account_params
      params.require(:veeresh_account).permit(:no_of_tickets_online, :no_of_tickets_box, :total_amt_per_day, :booking_id, :cinema_id, :user_id)
    end
end

app/helpers/veeresh_accounts_helper.rb
module VeereshAccountsHelper
end

app/views/veeresh_accounts/_form.html.erb
<%= form_for(@veeresh_account) do |f| %>
  <% if @veeresh_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@veeresh_account.errors.count, "error") %> prohibited this veeresh_account from being saved:</h2>

      <ul>
      <% @veeresh_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_of_tickets_online %><br>
    <%= f.number_field :no_of_tickets_online %>
  </div>
  <div class="field">
    <%= f.label :no_of_tickets_box %><br>
    <%= f.number_field :no_of_tickets_box %>
  </div>
  <div class="field">
    <%= f.label :total_amt_per_day %><br>
    <%= f.number_field :total_amt_per_day %>
  </div>

  <%= f.hidden_field :booking_id,:value => params[:booking_id] %>

  <%= f.hidden_field :cinema_id,:value => params[:cinema_id] %>

  <%= f.hidden_field :user_id,:value => params[:user_id] %>


<% end %>

app/views/veeresh_accounts/edit.html.erb
<h1>Editing Veeresh Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @veeresh_account %> |
<%= link_to 'Back', veeresh_accounts_path %>

app/views/veeresh_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Veeresh Accounts</h1>

<table>
  <thead>
    <tr>
      <th>No of tickets online</th>
      <th>No of tickets box</th>
      <th>Total amt per day</th>
      <th>Booking</th>
      <th>Cinema</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veeresh_accounts.each do |veeresh_account| %>
      <tr>
        <td><%= veeresh_account.no_of_tickets_online %></td>
        <td><%= veeresh_account.no_of_tickets_box %></td>
        <td><%= veeresh_account.total_amt_per_day %></td>
        <td><%= veeresh_account.booking_id %></td>
        <td><%= veeresh_account.cinema_id %></td>
        <td><%= veeresh_account.user_id %></td>
        <td><%= link_to 'Show', veeresh_account %></td>
        <td><%= link_to 'Edit', edit_veeresh_account_path(veeresh_account) %></td>
        <td><%= link_to 'Destroy', veeresh_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veeresh account', new_veeresh_account_path %>

app/views/veeresh_accounts/new.html.erb
<h1>New Veeresh Account</h1>

<%= render 'form' %>

<%= link_to 'Back', veeresh_accounts_path %>

app/views/veeresh_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No of tickets online:</strong>
  <%= @veeresh_account.no_of_tickets_online %>
</p>

<p>
  <strong>No of tickets box:</strong>
  <%= @veeresh_account.no_of_tickets_box %>
</p>

<p>
  <strong>Total amt per day:</strong>
  <%= @veeresh_account.total_amt_per_day %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @veeresh_account.booking_id %>
</p>

<p>
  <strong>Cinema:</strong>
  <%= @veeresh_account.cinema_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @veeresh_account.user_id %>
</p>

<%= link_to 'Edit', edit_veeresh_account_path(@veeresh_account) %> |
<%= link_to 'Back', veeresh_accounts_path %>